# Generated by Django 4.1.2 on 2022-10-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                ("value_url", models.URLField(blank=True, max_length=400, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_png", models.ImageField(blank=True, null=True, upload_to="")),
                ("value_jpg", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "value_object_field",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComponentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name="LandingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LandingTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.componenttemplate",
                    ),
                ),
                (
                    "landing_template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="components.landingtemplate",
                    ),
                ),
            ],
            options={
                "order_with_respect_to": "landing_template",
            },
        ),
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_pk", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "object_ctype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.landingtemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "object_ctype", "object_pk")},
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="components.landing",
                    ),
                ),
                (
                    "parent_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_components",
                        to="components.attribute",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.landingtemplateitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("landing", "template")},
            },
        ),
        migrations.CreateModel(
            name="AttributeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "TEXT"),
                            ("int", "INT"),
                            ("bool", "BOOL"),
                            ("url", "URL"),
                            ("png", "PNG"),
                            ("jpg", "JPG"),
                            ("component", "COMPONENT"),
                            ("components", "COMPONENTS"),
                            ("object", "OBJECT"),
                        ],
                        max_length=75,
                    ),
                ),
                (
                    "child_obj_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.componenttemplate",
                    ),
                ),
                (
                    "component_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="components.componenttemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attribute",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="components.component",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="components.attributetemplate",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="value_component",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_parent",
                to="components.component",
            ),
        ),
    ]
